from __future__ import annotations

from pathlib import Path

from orbitfabric.gen.runtime import build_runtime_contract, generate_cpp17_runtime_files
from orbitfabric.model.loader import MissionModelLoader

DEMO_MISSION = Path("examples/demo-3u/mission")


def test_generate_cpp17_runtime_headers(tmp_path: Path) -> None:
    model = MissionModelLoader().load(DEMO_MISSION)
    contract = build_runtime_contract(model)

    generated_files = generate_cpp17_runtime_files(contract, tmp_path)

    mission_ids = tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_ids.hpp"
    mission_enums = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_enums.hpp"
    )
    mission_registries = (
        tmp_path
        / "cpp17"
        / "include"
        / "orbitfabric"
        / "generated"
        / "mission_registries.hpp"
    )
    command_args = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "command_args.hpp"
    )
    adapter_interfaces = (
        tmp_path
        / "cpp17"
        / "include"
        / "orbitfabric"
        / "generated"
        / "adapter_interfaces.hpp"
    )

    assert generated_files == [
        mission_ids,
        mission_enums,
        mission_registries,
        command_args,
        adapter_interfaces,
    ]
    assert mission_ids.exists()
    assert mission_enums.exists()
    assert mission_registries.exists()
    assert command_args.exists()
    assert adapter_interfaces.exists()

    ids_content = mission_ids.read_text(encoding="utf-8")

    assert "// Generated by OrbitFabric. Do not edit manually." in ids_content
    assert "enum class CommandId : std::uint16_t" in ids_content
    assert "Invalid = 0" in ids_content
    assert "PayloadStartAcquisition" in ids_content
    assert "PayloadRadiationHistogram" in ids_content
    assert "enum class DataProductId : std::uint16_t" in ids_content
    assert "It is not flight software and contains no onboard behavior." in ids_content

    enums_content = mission_enums.read_text(encoding="utf-8")

    assert "enum class RuntimeValueType : std::uint16_t" in enums_content
    assert "Float32" in enums_content
    assert "Uint16" in enums_content

    registries_content = mission_registries.read_text(encoding="utf-8")

    assert "#include \"orbitfabric/generated/mission_ids.hpp\"" in registries_content
    assert "struct TelemetryDescriptor" in registries_content
    assert "struct CommandDescriptor" in registries_content
    assert "struct EventDescriptor" in registries_content
    assert "struct FaultDescriptor" in registries_content
    assert "struct DataProductDescriptor" in registries_content
    assert "inline constexpr std::array<TelemetryDescriptor" in registries_content
    assert "inline constexpr std::array<CommandDescriptor" in registries_content
    assert "inline constexpr std::array<DataProductDescriptor" in registries_content
    assert "CommandId::PayloadStartAcquisition" in registries_content
    assert "DataProductId::PayloadRadiationHistogram" in registries_content
    assert "It is not flight software and contains no onboard behavior." in registries_content

    command_args_content = command_args.read_text(encoding="utf-8")

    assert "struct PayloadStartAcquisitionArgs" in command_args_content
    assert "std::uint16_t duration_s;" in command_args_content
    assert "struct PayloadStopAcquisitionArgs" in command_args_content
    assert "struct EpsGetStatusArgs" in command_args_content
    assert "It is not flight software and contains no onboard behavior." in command_args_content

    adapter_content = adapter_interfaces.read_text(encoding="utf-8")

    assert "#include \"orbitfabric/generated/command_args.hpp\"" in adapter_content
    assert "enum class CommandResult : std::uint16_t" in adapter_content
    assert "class ICommandHandler" in adapter_content
    assert "virtual ~ICommandHandler() = default;" in adapter_content
    assert "virtual CommandResult handle_payload_start_acquisition" in adapter_content
    assert "const PayloadStartAcquisitionArgs& args" in adapter_content
    assert "class ITelemetrySink" in adapter_content
    assert "class IEventReporter" in adapter_content
    assert "class IFaultReporter" in adapter_content
    assert "It is not flight software and contains no onboard behavior." in adapter_content


def test_generate_cpp17_runtime_files_is_deterministic(tmp_path: Path) -> None:
    model = MissionModelLoader().load(DEMO_MISSION)
    contract = build_runtime_contract(model)

    generate_cpp17_runtime_files(contract, tmp_path)
    first_ids = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_ids.hpp"
    ).read_text(encoding="utf-8")
    first_enums = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_enums.hpp"
    ).read_text(encoding="utf-8")
    first_registries = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_registries.hpp"
    ).read_text(encoding="utf-8")
    first_command_args = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "command_args.hpp"
    ).read_text(encoding="utf-8")
    first_adapter_interfaces = (
        tmp_path
        / "cpp17"
        / "include"
        / "orbitfabric"
        / "generated"
        / "adapter_interfaces.hpp"
    ).read_text(encoding="utf-8")

    generate_cpp17_runtime_files(contract, tmp_path)
    second_ids = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_ids.hpp"
    ).read_text(encoding="utf-8")
    second_enums = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_enums.hpp"
    ).read_text(encoding="utf-8")
    second_registries = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_registries.hpp"
    ).read_text(encoding="utf-8")
    second_command_args = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "command_args.hpp"
    ).read_text(encoding="utf-8")
    second_adapter_interfaces = (
        tmp_path
        / "cpp17"
        / "include"
        / "orbitfabric"
        / "generated"
        / "adapter_interfaces.hpp"
    ).read_text(encoding="utf-8")

    assert first_ids == second_ids
    assert first_enums == second_enums
    assert first_registries == second_registries
    assert first_command_args == second_command_args
    assert first_adapter_interfaces == second_adapter_interfaces
