from __future__ import annotations

from pathlib import Path

from orbitfabric.gen.runtime import build_runtime_contract, generate_cpp17_runtime_files
from orbitfabric.model.loader import MissionModelLoader

DEMO_MISSION = Path("examples/demo-3u/mission")


def test_generate_cpp17_runtime_id_headers(tmp_path: Path) -> None:
    model = MissionModelLoader().load(DEMO_MISSION)
    contract = build_runtime_contract(model)

    generated_files = generate_cpp17_runtime_files(contract, tmp_path)

    mission_ids = tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_ids.hpp"
    mission_enums = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_enums.hpp"
    )

    assert generated_files == [mission_ids, mission_enums]
    assert mission_ids.exists()
    assert mission_enums.exists()

    ids_content = mission_ids.read_text(encoding="utf-8")

    assert "// Generated by OrbitFabric. Do not edit manually." in ids_content
    assert "enum class CommandId : std::uint16_t" in ids_content
    assert "Invalid = 0" in ids_content
    assert "PayloadStartAcquisition" in ids_content
    assert "PayloadRadiationHistogram" in ids_content
    assert "enum class DataProductId : std::uint16_t" in ids_content
    assert "It is not flight software and contains no onboard behavior." in ids_content

    enums_content = mission_enums.read_text(encoding="utf-8")

    assert "enum class RuntimeValueType : std::uint16_t" in enums_content
    assert "Float32" in enums_content
    assert "Uint16" in enums_content


def test_generate_cpp17_runtime_files_is_deterministic(tmp_path: Path) -> None:
    model = MissionModelLoader().load(DEMO_MISSION)
    contract = build_runtime_contract(model)

    generate_cpp17_runtime_files(contract, tmp_path)
    first_ids = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_ids.hpp"
    ).read_text(encoding="utf-8")
    first_enums = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_enums.hpp"
    ).read_text(encoding="utf-8")

    generate_cpp17_runtime_files(contract, tmp_path)
    second_ids = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_ids.hpp"
    ).read_text(encoding="utf-8")
    second_enums = (
        tmp_path / "cpp17" / "include" / "orbitfabric" / "generated" / "mission_enums.hpp"
    ).read_text(encoding="utf-8")

    assert first_ids == second_ids
    assert first_enums == second_enums
